import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Space_Grotesk as SpaceGrotesk } from 'next/font/google'

const spaceGrotesk = SpaceGrotesk({ 
  subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <div className='min-h-screen grid grid-cols-layout'>
          <Sidebar />

          <main className='px-4 pb-12 pt-8'>{children}</main>
        </div>
      </body>
    </html>
  )
}
